import React from 'react';
import { 
  Target, 
  Share,
  TrendingUp, 
  ShieldCheck, 
  Zap, 
  Landmark, 
  Wallet, 
  PieChart as PieIcon,
  AlertCircle,
  CheckCircle2,
  ArrowRight,
  Info,
  Activity,
  Lock,
  FileText,
  AlertTriangle,
  LineChart as LineIcon,
  TrendingDown,
  User,
  Sparkles,
  Calendar,
  Download,
  FileSpreadsheet
} from 'lucide-react';
import { 
  ResponsiveContainer, 
  PieChart, 
  Pie, 
  Cell, 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip as RechartsTooltip, 
  Legend,
  AreaChart,
  Area,
  LineChart,
  Line
} from 'recharts';
import ReactMarkdown from 'react-markdown';
import { motion } from 'motion/react';
import { FinancialPlan, AssetCategory, PortfolioState } from '../types';
import { formatCurrency, ASSET_COLORS } from '../constants';
import { toast } from 'sonner';
import { generateFinancialPlanPDF } from '../services/pdfService';
import ExportButtons from './ExportButtons';
import { handleDownloadCalculatorReport } from '../utils/exportUtils';

interface DetailedFinancialPlanViewProps {
  plan: FinancialPlan;
  portfolio: PortfolioState;
  isConsolidated?: boolean;
  onDownloadPDF?: () => void;
  onDownloadExcel?: () => void;
  onRefresh?: () => void;
}

const DetailedFinancialPlanView: React.FC<DetailedFinancialPlanViewProps> = ({ plan, portfolio, isConsolidated = false, onDownloadPDF, onDownloadExcel, onRefresh }) => {
  const [isSharing, setIsSharing] = React.useState(false);
  
  const handleShare = async () => {
    if (isSharing) return;
    setIsSharing(true);
    const toastId = toast.loading('Preparing your financial plan for sharing...');
    
    try {
      const doc = generateFinancialPlanPDF(plan, portfolio);
      const pdfBlob = doc.output('blob');
      const file = new File([pdfBlob], `Financial_Plan_${new Date().toISOString().split('T')[0]}.pdf`, { type: 'application/pdf' });

      if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: 'My Detailed Financial Plan',
          text: 'Check out my comprehensive financial roadmap generated by RH Wealth AI.',
        });
        toast.success('Shared successfully!', { id: toastId });
      } else {
        // Fallback for browsers that don't support file sharing
        const shareUrl = window.location.href;
        if (navigator.share) {
          await navigator.share({
            title: 'My Detailed Financial Plan',
            text: 'I just generated a comprehensive financial roadmap. Check out the RH Wealth app!',
            url: shareUrl
          });
          toast.success('Shared successfully!', { id: toastId });
        } else {
          // Final fallback: copy link or just alert
          await navigator.clipboard.writeText(shareUrl);
          toast.success('Link copied to clipboard! You can now share it manually.', { id: toastId });
        }
      }
    } catch (error) {
      console.error('Error sharing:', error);
      toast.error('Failed to share. Please try downloading the PDF instead.', { id: toastId });
    } finally {
      setIsSharing(false);
    }
  };

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-emerald-500 bg-emerald-50 border-emerald-100';
    if (score >= 60) return 'text-blue-500 bg-blue-50 border-blue-100';
    if (score >= 40) return 'text-amber-500 bg-amber-50 border-amber-100';
    return 'text-rose-500 bg-rose-50 border-rose-100';
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'Excellent': return <CheckCircle2 className="text-emerald-500" size={18} />;
      case 'Good': return <CheckCircle2 className="text-blue-500" size={18} />;
      case 'Fair': return <AlertCircle className="text-amber-500" size={18} />;
      case 'Poor': return <AlertCircle className="text-rose-500" size={18} />;
      default: return null;
    }
  };

  return (
    <div className="space-y-10 animate-in fade-in slide-in-from-bottom-4 duration-700 max-w-full overflow-hidden">
      {/* Cover Page */}
      <div className="bg-white rounded-[3rem] border border-slate-200 overflow-hidden shadow-2xl relative min-h-[90vh] flex flex-col items-center justify-center p-12 text-center">
        <div className="absolute inset-0 bg-slate-50/50 -z-10" />
        <div className="absolute top-0 right-0 p-8">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-emerald-600 rounded-bl-xl rotate-45" />
            <span className="text-xl font-black text-slate-800 tracking-tighter">Right Horizons</span>
          </div>
        </div>
        
        <div className="max-w-3xl space-y-12">
          <div className="w-full h-96 rounded-[3rem] overflow-hidden shadow-2xl relative">
            <img 
              src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1000" 
              alt="Planning"
              className="w-full h-full object-cover"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-slate-900/60 to-transparent" />
          </div>

          <div className="space-y-6">
            <h1 className="text-7xl font-black text-rose-500 uppercase tracking-tight leading-tight">
              A GOAL WITHOUT <br /> A PLAN
            </h1>
            <h2 className="text-6xl font-black text-slate-800 uppercase italic">
              IS JUST A WISH
            </h2>
            <div className="w-full h-2 bg-slate-200 mt-8" />
            <p className="text-xl text-slate-500 font-medium italic">Antonie De Saint-Exupery</p>
          </div>

          <div className="pt-20 grid grid-cols-1 md:grid-cols-2 gap-12 text-left border-t border-slate-100">
            <div>
              <p className="text-xs font-black text-slate-400 uppercase tracking-[0.2em] mb-1">Date</p>
              <p className="text-lg font-bold text-slate-900">{new Date().toLocaleDateString('en-GB')}</p>
            </div>
            <div className="md:text-right">
              <p className="text-xs font-black text-slate-400 uppercase tracking-[0.2em] mb-1">Prepared by</p>
              <p className="text-lg font-bold text-slate-900">Right Horizons</p>
            </div>
          </div>
        </div>
      </div>

      {/* Financial Planning Process */}
      <div className="bg-white p-10 md:p-20 rounded-[2.5rem] md:rounded-[3.5rem] border border-slate-200 shadow-sm space-y-12 md:space-y-16 text-center">
        <h2 className="text-2xl md:text-4xl font-black text-rose-500 uppercase tracking-widest bg-rose-50 inline-block px-8 md:px-12 py-3 md:py-4 rounded-2xl">
          FINANCIAL PLANNING PROCESS
        </h2>
        
        {/* Desktop Circular Layout */}
        <div className="hidden md:flex relative max-w-4xl mx-auto h-[600px] items-center justify-center">
          <div className="absolute w-[450px] h-[450px] border-4 border-slate-100 rounded-full" />
          
          {[
            { step: 1, text: "Determining your current financial situation." },
            { step: 2, text: "Developing financial goals." },
            { step: 3, text: "Identifying alternative courses of action." },
            { step: 4, text: "Evaluating alternatives." },
            { step: 5, text: "Creating & implementing a financial plan." },
            { step: 6, text: "Reevaluating and revising the plan." }
          ].map((item, idx) => {
            const angle = (idx * 60 - 90) * (Math.PI / 180);
            const radius = 240;
            const x = Math.cos(angle) * radius;
            const y = Math.sin(angle) * radius;
            
            return (
              <motion.div 
                key={idx}
                initial={{ opacity: 0, scale: 0.8 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                style={{ 
                  position: 'absolute',
                  left: '50%',
                  top: '50%',
                  transform: `translate(calc(-50% + ${x}px), calc(-50% + ${y}px))`
                }}
                className="w-60 p-6 bg-wealth-navy text-white rounded-[2rem] shadow-xl z-20 border-4 border-white"
              >
                <div className="absolute -top-4 left-1/2 -translate-x-1/2 w-8 h-8 bg-rose-500 rounded-full flex items-center justify-center font-bold text-xs ring-4 ring-white">
                  {item.step}
                </div>
                <p className="text-sm font-bold leading-relaxed">{item.text}</p>
              </motion.div>
            );
          })}
        </div>

        {/* Mobile List Layout */}
        <div className="md:hidden flex flex-col gap-6 text-left">
          {[
            { step: 1, text: "Determining your current financial situation." },
            { step: 2, text: "Developing financial goals." },
            { step: 3, text: "Identifying alternative courses of action." },
            { step: 4, text: "Evaluating alternatives." },
            { step: 5, text: "Creating & implementing a financial plan." },
            { step: 6, text: "Reevaluating and revising the plan." }
          ].map((item, idx) => (
            <div key={idx} className="flex gap-4 p-5 bg-wealth-navy text-white rounded-2xl relative border-2 border-slate-100 shadow-lg">
              <div className="w-10 h-10 bg-rose-500 rounded-xl flex items-center justify-center font-black shrink-0">
                {item.step}
              </div>
              <p className="text-sm font-bold leading-relaxed py-1">{item.text}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="bg-gradient-to-br from-wealth-navy to-slate-800 rounded-[3rem] p-12 text-white shadow-2xl relative overflow-hidden break-words">
        <div className="absolute top-0 right-0 w-96 h-96 bg-wealth-gold/10 blur-[120px] rounded-full -mr-48 -mt-48" />
        <div className="absolute bottom-0 left-0 w-64 h-64 bg-indigo-500/10 blur-[80px] rounded-full -ml-32 -mb-32" />
        
        <div className="relative z-10 space-y-12">
          <div className="flex flex-col lg:flex-row justify-between items-start gap-10">
            <div className="space-y-6 flex-1">
              <div className="flex items-center gap-4">
                <span className="px-4 py-1.5 bg-wealth-gold/20 text-wealth-gold rounded-full text-[10px] font-black uppercase tracking-[0.3em] border border-wealth-gold/30">
                  Confidential Report
                </span>
                <span className="text-slate-400 text-xs font-medium">Edition {new Date().getFullYear()} / {new Date().getFullYear() + 1}</span>
              </div>
              <h1 className="text-6xl font-black tracking-tight leading-none italic uppercase">
                Strategic <br /> Wealth <br /> <span className="text-wealth-gold non-italic">Roadmap</span>
              </h1>
              <p className="text-slate-300 text-lg font-medium max-w-xl leading-relaxed">
                Institutional-grade financial architecture tailored for the {portfolio.familyMembers.find(m => m.relationship === 'Self')?.name || 'Client'} Family Nucleus.
              </p>
            </div>
            
            <div className="flex flex-col gap-4 w-full lg:w-72">
              <div className="p-6 bg-white/10 backdrop-blur-md rounded-[2.5rem] border border-white/10 space-y-4">
                <div className="flex justify-between items-center text-right">
                  <div>
                    <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Score</p>
                    <p className="text-3xl font-black text-wealth-gold">{(plan.portfolioScorecard?.reduce((acc, s) => acc + s.score, 0) / (plan.portfolioScorecard?.length || 1)).toFixed(1)}</p>
                  </div>
                  <div className="w-12 h-12 bg-white/20 rounded-2xl flex items-center justify-center">
                    <Activity className="text-white" size={24} />
                  </div>
                </div>
                <div className="h-1 bg-white/10 rounded-full">
                  <div 
                    className="h-full bg-wealth-gold rounded-full shadow-[0_0_10px_rgba(234,179,8,0.5)] transition-all duration-1000" 
                    style={{ width: `${(plan.portfolioScorecard?.reduce((acc, s) => acc + s.score, 0) / (plan.portfolioScorecard?.length || 1))}%` }}
                  />
                </div>
                <p className="text-[10px] font-bold text-slate-300 text-center uppercase tracking-widest">Resilience: Strong</p>
              </div>

              <div className="grid grid-cols-1 gap-3">
                <div className="flex gap-2">
                  {onDownloadPDF && (
                    <button 
                      onClick={onDownloadPDF}
                      className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-rose-600 text-white rounded-xl font-bold hover:bg-rose-700 transition-all shadow-lg shadow-rose-900/20 text-xs"
                    >
                      <Download size={14} />
                      Download PDF
                    </button>
                  )}
                  {onDownloadExcel && (
                    <button 
                      onClick={onDownloadExcel}
                      className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-emerald-600 text-white rounded-xl font-bold hover:bg-emerald-700 transition-all shadow-lg shadow-emerald-900/20 text-xs"
                    >
                      <FileSpreadsheet size={14} />
                      Excel
                    </button>
                  )}
                </div>
                <ExportButtons 
                  title="Comprehensive Financial Plan"
                  variant="dark"
                  onDownload={handleDownloadCalculatorReport}
                  inputs={[
                    ['Plan Level', isConsolidated ? 'Consolidated' : 'Standard'],
                    ['Risk Profile', plan.riskProfileAnalysis.profile],
                    ['Asset Allocation Recommendation', plan.riskProfileAnalysis.assetAllocationSuggestion]
                  ]}
                  results={[
                    ['Net Worth', formatCurrency(plan.netWorthAnalysis.netWorth)],
                    ['Savings Rate', `${plan.cashFlowAnalysis.savingsRate}%`]
                  ]}
                />
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-12 border-t border-white/10">
            <div>
              <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2">Primary Member</p>
              <p className="text-xl font-black text-white">{portfolio.familyMembers.find(m => m.relationship === 'Self')?.name || 'Client'}</p>
            </div>
            <div>
              <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2">Architected by</p>
              <p className="text-xl font-black text-white">AI Strategy Engine</p>
            </div>
            <div>
              <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-2">Generation Date</p>
              <p className="text-xl font-black text-white">{new Date(plan.lastGenerated).toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Life Phases */}
      <div className="bg-white p-12 rounded-[3.5rem] border border-slate-200 shadow-sm space-y-12 overflow-hidden">
        <div className="text-center">
          <h2 className="text-4xl font-black text-rose-500 uppercase tracking-[0.3em] bg-rose-50 inline-block px-12 py-4 rounded-2xl mb-4">
            LIFE PHASES
          </h2>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-12">
            <div className="h-[400px] w-full relative">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={[
                  { age: 20, wealth: 0, phase: 'Accumulation' },
                  { age: 30, wealth: 20, phase: 'Accumulation' },
                  { age: 40, wealth: 50, phase: 'Accumulation' },
                  { age: 50, wealth: 85, phase: 'Accumulation' },
                  { age: 60, wealth: 100, phase: 'Transition' },
                  { age: 70, wealth: 70, phase: 'Distribution' },
                  { age: 80, wealth: 40, phase: 'Distribution' },
                  { age: 90, wealth: 15, phase: 'Distribution' },
                ]}>
                  <defs>
                    <linearGradient id="colorWealth" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#f43f5e" stopOpacity={0.1}/>
                      <stop offset="95%" stopColor="#f43f5e" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <XAxis dataKey="age" label={{ value: 'AGE', position: 'insideBottom', offset: -10, fontSize: 10, fontWeight: 'bold' }} />
                  <YAxis label={{ value: 'WEALTH (%)', angle: -90, position: 'insideLeft', fontSize: 10, fontWeight: 'bold' }} />
                  <RechartsTooltip />
                  <Area type="monotone" dataKey="wealth" stroke="#f43f5e" strokeWidth={4} fillOpacity={1} fill="url(#colorWealth)" />
                </AreaChart>
              </ResponsiveContainer>
              
              {/* Annotation Overlays */}
              <div className="absolute top-1/4 left-[15%] text-center">
                <span className="bg-emerald-500 text-white px-4 py-1 rounded-lg text-[10px] font-black uppercase shadow-lg">Accumulation Phase</span>
              </div>
              <div className="absolute top-1/4 right-[15%] text-center">
                <span className="bg-rose-500 text-white px-4 py-1 rounded-lg text-[10px] font-black uppercase shadow-lg">Distribution Phase</span>
              </div>
              
              {/* Marker for Current Age */}
              {portfolio.familyMembers.find(m => m.relationship === 'Self')?.age && (
                <div 
                  className="absolute bottom-0 border-l-2 border-rose-500 h-full flex flex-col items-center z-10 pointer-events-none"
                  style={{ left: `${Math.max(10, Math.min(90, ((portfolio.familyMembers.find(m => m.relationship === 'Self')?.age || 20) - 20) / 0.7))}%` }}
                >
                  <div className="bg-rose-500 text-white px-2 py-1 rounded-md text-[10px] font-black uppercase mt-12 whitespace-nowrap shadow-lg">
                    Current Age: {portfolio.familyMembers.find(m => m.relationship === 'Self')?.age}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-8">
          <div className="p-8 bg-slate-50 rounded-[2.5rem] border border-slate-100">
            <h4 className="text-xl font-black text-slate-800 mb-4 flex items-center gap-3">
              <div className="w-3 h-3 bg-emerald-500 rounded-full" />
              ACCUMULATION PHASE
            </h4>
            <p className="text-sm text-slate-600 leading-relaxed font-medium">
              In this phase the individual starts earning money. This is also the phase when the individual has the capacity to accumulate wealth towards various goals. In this phase, the individual can typically afford to have a higher risk appetite since the investment horizon can be long term.
            </p>
          </div>
          <div className="p-8 bg-slate-50 rounded-[2.5rem] border border-slate-100">
            <h4 className="text-xl font-black text-slate-800 mb-4 flex items-center gap-3">
              <div className="w-3 h-3 bg-rose-500 rounded-full" />
              DISTRIBUTION PHASE
            </h4>
            <p className="text-sm text-slate-600 leading-relaxed font-medium">
              In this phase the individual stops earning money. The accumulated wealth is utilized towards fulfillment of a long retirement phase. During this phase, the risk appetite may skew towards less risk investments.
            </p>
          </div>
        </div>
      </div>

      <div className="bg-white p-12 rounded-[3.5rem] border border-slate-200 shadow-sm relative overflow-hidden">
        <div className="absolute top-0 right-0 p-8">
          <Sparkles className="text-amber-200" size={60} />
        </div>
        <div className="flex items-center gap-3 mb-10">
          <div className="p-3 bg-indigo-50 text-indigo-600 rounded-2xl">
            <Zap size={24} />
          </div>
          <div>
            <h3 className="text-2xl font-black text-slate-900 tracking-tight">Executive Summary</h3>
            <p className="text-xs text-slate-400 font-bold uppercase tracking-[0.2em] leading-loose">The Strategic Macro Perspective</p>
          </div>
        </div>
        <div className="prose prose-slate max-w-none text-slate-600 leading-relaxed italic text-lg p-6 bg-slate-50 rounded-[2.5rem] border border-slate-100">
          <ReactMarkdown>{plan.executiveSummary}</ReactMarkdown>
        </div>
      </div>

      {/* Portfolio Scorecard - Bento Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {plan.portfolioScorecard && plan.portfolioScorecard.length > 0 ? (
          plan.portfolioScorecard.map((item, idx) => (
            <motion.div 
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
              className="bg-white p-6 rounded-[2rem] border border-slate-200 shadow-sm hover:shadow-md transition-shadow"
            >
              <div className="flex justify-between items-start mb-4">
                <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">{item.category}</span>
                {getStatusIcon(item.status)}
              </div>
              <div className="flex items-end gap-2 mb-4">
                <span className="text-4xl font-black text-slate-900">{item.score}</span>
                <span className="text-sm font-bold text-slate-400 mb-1">/100</span>
              </div>
              <div className="w-full h-1.5 bg-slate-100 rounded-full overflow-hidden mb-4">
                <div 
                  className={`h-full rounded-full transition-all duration-1000 ${
                    item.score >= 80 ? 'bg-emerald-500' : 
                    item.score >= 60 ? 'bg-blue-500' : 
                    item.score >= 40 ? 'bg-amber-500' : 'bg-rose-500'
                  }`}
                  style={{ width: `${isNaN(item.score) ? 0 : item.score}%` }}
                />
              </div>
              <p className="text-xs text-slate-600 leading-relaxed font-medium">
                {item.observation}
              </p>
            </motion.div>
          ))
        ) : (
          <div className="md:col-span-2 lg:col-span-4 bg-slate-50 p-8 rounded-[2rem] border border-dashed border-slate-300 text-center text-slate-500">
            No portfolio scorecard data available. Generate a new plan to see insights.
          </div>
        )}
      </div>

      {/* Family Member Details Section - New */}
      <div className="bg-white p-10 rounded-[3rem] border border-slate-200 shadow-sm space-y-10">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-3 bg-indigo-50 text-indigo-600 rounded-2xl">
              <User size={24} />
            </div>
            <div>
              <h3 className="text-2xl font-black text-slate-900 tracking-tight">Family Dynamics</h3>
              <p className="text-xs text-slate-400 font-bold uppercase tracking-[0.2em]">Profile & Compliance Status</p>
            </div>
          </div>
          <div className="text-right">
            <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Prepared for</p>
            <p className="text-lg font-black text-wealth-navy">{portfolio.familyMembers.find(m => m.relationship === 'Self')?.name || 'Client'}</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {plan.familyDetails?.map((member, idx) => (
            <div key={idx} className="p-8 bg-slate-50/50 rounded-[2.5rem] border border-slate-100 relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-24 h-24 bg-indigo-500/5 group-hover:bg-indigo-500/10 transition-colors blur-2xl rounded-full -mr-12 -mt-12" />
              <div className="flex items-start justify-between relative z-10">
                <div className="flex items-start gap-6">
                  <div className="w-20 h-20 bg-white rounded-3xl shadow-sm flex items-center justify-center p-4 border border-slate-100">
                    <User size={40} className="text-slate-300" />
                  </div>
                  <div className="space-y-4">
                    <div>
                      <h4 className="text-xl font-black text-slate-900 leading-tight">{member.name}</h4>
                      <div className="flex items-center gap-3 mt-1">
                        <span className="text-xs font-bold text-slate-500">{member.age} Yrs</span>
                        <div className="w-1 h-1 bg-slate-300 rounded-full" />
                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{member.relationship}</span>
                      </div>
                    </div>
                    <div className="space-y-1">
                      <p className="text-xs font-medium text-slate-500">{member.email || 'No Email provided'}</p>
                      <p className="text-xs font-medium text-slate-500">PAN suffix: <span className="font-bold text-slate-700">{member.panSuffix || 'XXXXX'}</span></p>
                    </div>
                  </div>
                </div>
                <div className={`px-4 py-1.5 rounded-full text-[9px] font-black uppercase tracking-widest border ${
                  member.kycStatus === 'Verified' ? 'bg-emerald-50 text-emerald-600 border-emerald-100' :
                  'bg-amber-50 text-amber-600 border-amber-100'
                }`}>
                  KYC {member.kycStatus}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Analysis Column */}
        <div className="lg:col-span-2 space-y-8">
          
          {/* Net Worth & Cash Flow Side-by-Side */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-sm break-words">
              <div className="flex items-center justify-between mb-10">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 bg-emerald-50 text-emerald-600 rounded-2xl">
                    <Landmark size={22} />
                  </div>
                  <div>
                    <h3 className="font-bold text-slate-900">Net Worth Analysis</h3>
                    <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Asset vs Liability Breakdown</p>
                  </div>
                </div>
                <div className="text-right">
                  <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mb-1">Current Net Worth</p>
                  <p className="text-2xl font-black text-emerald-600">{formatCurrency(plan.netWorthAnalysis?.netWorth || 0)}</p>
                </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
                {/* Assets Breakdown */}
                <div>
                  <h4 className="text-xs font-black text-slate-400 uppercase tracking-[0.2em] mb-6 flex items-center gap-2">
                    <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full" />
                    Asset Allocation
                  </h4>
                  <div className="h-[220px] w-full mb-6">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie
                          data={Object.entries(plan.netWorthAnalysis?.assetBreakdown || {}).map(([name, value]) => ({ name, value }))}
                          cx="50%"
                          cy="50%"
                          innerRadius={60}
                          outerRadius={90}
                          paddingAngle={4}
                          dataKey="value"
                        >
                          {Object.keys(plan.netWorthAnalysis?.assetBreakdown || {}).map((name, index) => (
                            <Cell key={name} fill={ASSET_COLORS[name as AssetCategory] || `hsl(${index * 60 + 140}, 70%, 50%)`} />
                          ))}
                        </Pie>
                        <RechartsTooltip 
                          formatter={(value: number) => formatCurrency(value)}
                          contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1)' }}
                        />
                        <Legend verticalAlign="bottom" height={36} iconType="circle" wrapperStyle={{ fontSize: '10px', fontWeight: 'bold' }} />
                      </PieChart>
                    </ResponsiveContainer>
                  </div>
                </div>

                {/* Liabilities Breakdown */}
                <div>
                  <h4 className="text-xs font-black text-slate-400 uppercase tracking-[0.2em] mb-6 flex items-center gap-2">
                    <div className="w-1.5 h-1.5 bg-rose-500 rounded-full" />
                    Liability Structure
                  </h4>
                  <div className="h-[220px] w-full mb-6">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie
                          data={Object.entries(plan.netWorthAnalysis?.liabilityBreakdown || {}).map(([name, value]) => ({ name, value }))}
                          cx="50%"
                          cy="50%"
                          innerRadius={60}
                          outerRadius={90}
                          paddingAngle={4}
                          dataKey="value"
                        >
                          {Object.keys(plan.netWorthAnalysis?.liabilityBreakdown || {}).map((name, index) => (
                            <Cell key={name} fill={`hsl(${index * 40 + 0}, 70%, 60%)`} />
                          ))}
                        </Pie>
                        <RechartsTooltip 
                          formatter={(value: number) => formatCurrency(value)}
                          contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1)' }}
                        />
                        <Legend verticalAlign="bottom" height={36} iconType="circle" wrapperStyle={{ fontSize: '10px', fontWeight: 'bold' }} />
                      </PieChart>
                    </ResponsiveContainer>
                  </div>
                </div>
              </div>

              <div className="mt-8 p-5 bg-slate-50 rounded-2xl border border-slate-100 text-xs text-slate-600 leading-relaxed italic break-words">
                <ReactMarkdown>{plan.netWorthAnalysis?.analysis || ''}</ReactMarkdown>
              </div>

              {/* Detailed Asset Table - New */}
              <div className="mt-10 overflow-x-auto rounded-3xl border border-slate-100">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-wealth-navy text-white">
                      <th className="px-6 py-4 text-[10px] font-black uppercase tracking-widest">Asset Name</th>
                      <th className="px-6 py-4 text-[10px] font-black uppercase tracking-widest text-right">Invested</th>
                      <th className="px-6 py-4 text-[10px] font-black uppercase tracking-widest text-right">Current Value</th>
                      <th className="px-6 py-4 text-[10px] font-black uppercase tracking-widest text-right">Allocation %</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {plan.netWorthAnalysis?.detailedAssetTable?.map((row, idx) => (
                      <tr key={idx} className="hover:bg-slate-50 transition-colors">
                        <td className="px-6 py-4 text-xs font-bold text-slate-700">{row.name}</td>
                        <td className="px-6 py-4 text-xs font-bold text-slate-600 text-right">{!row.invested || row.invested === 0 ? '-' : formatCurrency(row.invested)}</td>
                        <td className="px-6 py-4 text-xs font-black text-wealth-navy text-right">{formatCurrency(row.current)}</td>
                        <td className="px-6 py-4 text-xs font-bold text-slate-500 text-right">{(row.allocation || 0).toFixed(2)}%</td>
                      </tr>
                    ))}
                    <tr className="bg-slate-100/50 font-black">
                      <td className="px-6 py-4 text-xs text-slate-900 uppercase tracking-widest">Total Assets</td>
                      <td className="px-6 py-4 text-xs text-slate-600 text-right">
                        {formatCurrency(plan.netWorthAnalysis?.detailedAssetTable?.reduce((a, b) => a + (b.invested || 0), 0) || 0)}
                      </td>
                      <td className="px-6 py-4 text-xs text-wealth-navy text-right">
                        {formatCurrency(plan.netWorthAnalysis?.totalAssets || 0)}
                      </td>
                      <td className="px-6 py-4 text-xs text-slate-400 text-right">100%</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div className="bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-sm">
              <div className="flex items-center gap-3 mb-8">
                <div className="p-2.5 bg-blue-50 text-blue-600 rounded-2xl">
                  <Wallet size={22} />
                </div>
                <div>
                  <h3 className="font-bold text-slate-900">Cash Flow Health</h3>
                  <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Income vs Expenses</p>
                </div>
              </div>

              <div className="flex items-center justify-between mb-8">
                <div>
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Monthly Surplus</p>
                  <p className="text-3xl font-black text-blue-600">{formatCurrency(plan.cashFlowAnalysis?.surplus || 0)}</p>
                </div>
                <div className="text-right">
                  <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Savings Rate</p>
                  <p className="text-lg font-bold text-slate-900">{isNaN(plan.cashFlowAnalysis?.savingsRate || 0) ? '0.0' : (plan.cashFlowAnalysis?.savingsRate || 0).toFixed(1)}%</p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
                <div className="space-y-4">
                  <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
                    <TrendingUp size={14} className="text-emerald-500" />
                    Inflow Breakdown
                  </h4>
                  <div className="space-y-2">
                    {plan.cashFlowAnalysis?.inflowBreakdown?.map((item, i) => (
                      <div key={i} className="flex justify-between items-center p-3 bg-emerald-50/30 rounded-xl border border-emerald-50">
                        <span className="text-xs font-bold text-slate-700">{item.category}</span>
                        <span className="text-xs font-black text-emerald-600">{formatCurrency(item.amount)}</span>
                      </div>
                    ))}
                  </div>
                </div>
                <div className="space-y-4">
                  <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
                    <TrendingDown size={14} className="text-rose-500" />
                    Outflow Breakdown
                  </h4>
                  <div className="space-y-2">
                    {plan.cashFlowAnalysis?.outflowBreakdown?.map((item, i) => (
                      <div key={i} className="flex justify-between items-center p-3 bg-rose-50/30 rounded-xl border border-rose-50">
                        <span className="text-xs font-bold text-slate-700">{item.category}</span>
                        <span className="text-xs font-black text-rose-600">{formatCurrency(item.amount)}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <div className="p-5 bg-slate-50 rounded-2xl border border-slate-100 text-xs text-slate-600 leading-relaxed italic break-words">
                <ReactMarkdown>{plan.cashFlowAnalysis?.analysis || ''}</ReactMarkdown>
              </div>
            </div>
          </div>

          {/* Tax Optimization Strategy */}
          <div className="bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-sm break-words">
            <div className="flex items-center gap-3 mb-8">
              <div className="p-2.5 bg-indigo-50 text-indigo-600 rounded-2xl">
                <Zap size={22} />
              </div>
              <div>
                <h3 className="font-bold text-slate-900">Tax Optimization Strategy</h3>
                <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Budget 2024-25 Compliance</p>
              </div>
            </div>
            <div className="prose prose-sm max-w-none text-slate-600 leading-relaxed">
              <ReactMarkdown>{plan.taxOptimizationStrategy}</ReactMarkdown>
            </div>
          </div>

          {/* Goal Gap Analysis - Detailed */}
          <div className="bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-sm">
            <div className="flex items-center justify-between mb-10">
              <div className="flex items-center gap-3">
                <div className="p-2.5 bg-amber-50 text-amber-600 rounded-2xl">
                  <Target size={22} />
                </div>
                <div>
                  <h3 className="font-bold text-slate-900">Goal Gap Analysis</h3>
                  <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Future Cost Projections</p>
                </div>
              </div>
              <div className="px-4 py-1.5 bg-slate-100 rounded-full text-[10px] font-black text-slate-500 uppercase tracking-widest">
                {plan.goalGapAnalysis?.length || 0} Goals Tracked
              </div>
            </div>

            <div className="space-y-8">
              {plan.goalGapAnalysis?.map((goal, idx) => (
                <div key={idx} className="group p-8 bg-slate-50 rounded-[2rem] border border-slate-100 hover:border-indigo-200 transition-colors break-words">
                  <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-8">
                    <div>
                      <h4 className="text-xl font-black text-slate-900 mb-1">{goal.goalName}</h4>
                      <div className="flex items-center gap-4">
                        <span className="text-xs text-slate-500 font-medium">In {goal.yearsRemaining} Years</span>
                        <div className="w-1.5 h-1.5 bg-slate-300 rounded-full" />
                        <span className="text-xs text-slate-500 font-medium">Inflation Adj. Cost: {formatCurrency(goal.inflationAdjustedCost)}</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="text-right">
                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-0.5">Gap</p>
                        <p className="text-sm font-bold text-rose-600">{formatCurrency(goal.gap)}</p>
                      </div>
                      <span className={`px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest ${
                        goal.status === 'On Track' ? 'bg-emerald-100 text-emerald-700' :
                        goal.status === 'At Risk' ? 'bg-amber-100 text-amber-700' :
                        'bg-rose-100 text-rose-700'
                      }`}>
                        {goal.status}
                      </span>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
                    <div className="md:col-span-2">
                      <div className="flex justify-between text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">
                        <span>Progress</span>
                        <span>{isNaN(goal.currentAmount / goal.targetAmount) || !isFinite(goal.currentAmount / goal.targetAmount) ? '0.0' : ((goal.currentAmount / goal.targetAmount) * 100).toFixed(1)}%</span>
                      </div>
                      <div className="relative h-3 bg-slate-200 rounded-full overflow-hidden">
                        <motion.div 
                          initial={{ width: 0 }}
                          animate={{ width: `${isNaN(goal.currentAmount / goal.targetAmount) || !isFinite(goal.currentAmount / goal.targetAmount) ? 0 : Math.min(100, (goal.currentAmount / goal.targetAmount) * 100)}%` }}
                          transition={{ duration: 1.5, ease: "easeOut" }}
                          className={`absolute top-0 left-0 h-full rounded-full ${
                            goal.status === 'On Track' ? 'bg-emerald-500' :
                            goal.status === 'At Risk' ? 'bg-amber-500' :
                            'bg-rose-500'
                          }`}
                        />
                      </div>
                    </div>
                    <div className="flex flex-col justify-center">
                      <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1 text-center md:text-left">Target Date</p>
                      <p className="text-lg font-black text-slate-900 text-center md:text-left">
                        {new Date().getFullYear() + goal.yearsRemaining}
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start gap-3 p-4 bg-white rounded-2xl border border-slate-100 break-words">
                    <div className="p-1.5 bg-indigo-50 text-indigo-600 rounded-lg shrink-0">
                      <Zap size={14} />
                    </div>
                    <p className="text-xs text-slate-600 leading-relaxed">
                      <span className="font-bold text-indigo-600">Strategic Recommendation:</span> {goal.recommendation}
                    </p>
                  </div>

                  {/* Goal Mapping Deep Dive - New */}
                  {goal.mapping && (
                    <div className="mt-8 grid grid-cols-1 lg:grid-cols-2 gap-8 pt-8 border-t border-slate-100">
                      <div className="space-y-6">
                        <div className="flex items-center justify-between">
                          <h5 className="text-[10px] font-black text-indigo-400 uppercase tracking-widest">Asset Allocation for Goal</h5>
                          <span className="text-xl font-black text-indigo-600">{goal.mapping.achievedPercentage}% Achievable</span>
                        </div>
                        <div className="grid grid-cols-2 gap-4">
                          <div className="p-4 bg-white rounded-2xl border border-slate-100">
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Equity Req.</p>
                            <p className="text-sm font-black text-slate-700">{formatCurrency(goal.mapping.equityRequirement)}</p>
                          </div>
                          <div className="p-4 bg-white rounded-2xl border border-slate-100">
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Debt Req.</p>
                            <p className="text-sm font-black text-slate-700">{formatCurrency(goal.mapping.debtRequirement)}</p>
                          </div>
                        </div>
                        <div className="p-4 bg-indigo-600 rounded-2xl text-white shadow-lg shadow-indigo-100 flex justify-between items-center">
                          <div>
                            <p className="text-[9px] font-black uppercase tracking-widest opacity-70">Suggested Monthly SIP</p>
                            <p className="text-lg font-black">{formatCurrency(goal.mapping.monthlySip)}</p>
                          </div>
                          <div className="text-right border-l border-white/20 pl-4">
                            <p className="text-[9px] font-black uppercase tracking-widest opacity-70">Lumpsum req.</p>
                            <p className="text-sm font-bold">{formatCurrency(goal.mapping.lumpsum)}</p>
                          </div>
                        </div>
                      </div>

                      <div className="space-y-4">
                        <h5 className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Current Allocated Assets</h5>
                        <div className="space-y-2">
                          {goal.mapping.allocatedAssets.map((asset, i) => (
                            <div key={i} className="flex justify-between items-center p-3 bg-white rounded-xl border border-slate-100">
                              <span className="text-xs font-bold text-slate-600 max-w-[150px] truncate">{asset.name}</span>
                              <span className="text-xs font-black text-slate-900">{formatCurrency(asset.value)}</span>
                            </div>
                          ))}
                        </div>
                        <div className="p-4 bg-amber-50/50 rounded-2xl border border-amber-100/50">
                          <p className="text-[9px] font-black text-amber-600 uppercase tracking-widest mb-2 flex items-center gap-2">
                            <Info size={12} /> Planner Notes
                          </p>
                          <ul className="space-y-1">
                            {goal.mapping.plannerNotes.map((note, i) => (
                              <li key={i} className="text-[10px] text-amber-800 font-medium leading-relaxed">• {note}</li>
                            ))}
                          </ul>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Insurance Gap Analysis */}
          <div className="bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-sm">
            <div className="flex items-center gap-3 mb-10">
              <div className="p-2.5 bg-rose-50 text-rose-600 rounded-2xl">
                <ShieldCheck size={22} />
              </div>
              <div>
                <h3 className="font-bold text-slate-900">Insurance Gap Analysis</h3>
                <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Protection Adequacy</p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {plan.insuranceGapAnalysis?.map((gap, idx) => (
                <div key={idx} className="p-6 bg-slate-50 rounded-3xl border border-slate-100">
                  <h4 className="font-bold text-slate-900 mb-6 flex items-center gap-2">
                    {gap.type} Insurance
                    {gap.gap > 0 ? (
                      <span className="px-2 py-0.5 bg-rose-100 text-rose-600 text-[9px] font-black uppercase rounded-md">Gap Identified</span>
                    ) : (
                      <span className="px-2 py-0.5 bg-emerald-100 text-emerald-600 text-[9px] font-black uppercase rounded-md">Adequate</span>
                    )}
                  </h4>
                  
                  <div className="space-y-4 mb-6">
                    <div className="flex justify-between items-center">
                      <span className="text-xs text-slate-500">Required Cover</span>
                      <span className="font-bold text-slate-900">{formatCurrency(gap.required)}</span>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-xs text-slate-500">Current Cover</span>
                      <span className="font-bold text-emerald-600">{formatCurrency(gap.current)}</span>
                    </div>
                    <div className="h-px bg-slate-200" />
                    <div className="flex justify-between items-center">
                      <span className="text-xs font-bold text-slate-900">Shortfall</span>
                      <span className={`font-black ${gap.gap > 0 ? 'text-rose-600' : 'text-emerald-600'}`}>
                        {gap.gap > 0 ? formatCurrency(gap.gap) : 'Nil'}
                      </span>
                    </div>
                  </div>

                  <p className="text-xs text-slate-600 leading-relaxed italic break-words">
                    {gap.analysis}
                  </p>

                  {/* Need Based Analysis - New */}
                  {gap.needBasedAnalysis && gap.needBasedAnalysis.length > 0 && (
                    <div className="mt-8 overflow-hidden rounded-2xl border border-slate-100">
                      <table className="w-full text-left">
                        <thead>
                          <tr className="bg-slate-100/50">
                            <th className="px-4 py-3 text-[9px] font-black uppercase tracking-widest text-slate-500">Particulars</th>
                            <th className="px-4 py-3 text-[9px] font-black uppercase tracking-widest text-slate-500 text-right">Amount</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-50">
                          {gap.needBasedAnalysis.map((item, i) => (
                            <tr key={i}>
                              <td className="px-4 py-2 text-[11px] font-medium text-slate-600">{item.label}</td>
                              <td className="px-4 py-2 text-[11px] font-black text-slate-700 text-right">{formatCurrency(item.amount)}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Sidebar Column */}
        <div className="space-y-8">
          {/* Risk Profile Gauge */}
          <div className="bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-sm overflow-hidden relative">
            <div className="flex items-center gap-3 mb-8">
              <div className="p-2.5 bg-indigo-50 text-indigo-600 rounded-2xl">
                <Activity size={22} />
              </div>
              <div>
                <h3 className="font-bold text-slate-900">Risk Profile</h3>
                <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Tolerance & Suitability</p>
              </div>
            </div>

            <div className="flex flex-col items-center mb-8">
              <div className="relative w-48 h-24 overflow-hidden">
                <div className="absolute top-0 left-0 w-48 h-48 border-[16px] border-slate-100 rounded-full" />
                <div 
                  className={`absolute top-0 left-0 w-48 h-48 border-[16px] rounded-full transition-all duration-1000 ${
                    (plan.riskProfileAnalysis?.score || 0) >= 80 ? 'border-rose-500' :
                    (plan.riskProfileAnalysis?.score || 0) >= 60 ? 'border-amber-500' :
                    (plan.riskProfileAnalysis?.score || 0) >= 40 ? 'border-blue-500' : 'border-emerald-500'
                  }`}
                  style={{ 
                    clipPath: 'inset(0 0 50% 0)',
                    transform: `rotate(${((plan.riskProfileAnalysis?.score || 0) / 100) * 180 - 180}deg)`
                  }}
                />
                <div className="absolute bottom-0 left-1/2 -translate-x-1/2 text-center">
                  <p className="text-2xl font-black text-slate-900">{plan.riskProfileAnalysis?.profile || 'N/A'}</p>
                  <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Score: {plan.riskProfileAnalysis?.score || 0}</p>
                </div>
              </div>
            </div>

            <div className="space-y-4">
              <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100 break-words">
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Description</p>
                <p className="text-xs text-slate-600 leading-relaxed">{plan.riskProfileAnalysis?.description || 'No description available.'}</p>
              </div>
              <div className="p-4 bg-indigo-50 rounded-2xl border border-indigo-100 break-words">
                <p className="text-[10px] font-black text-indigo-400 uppercase tracking-widest mb-1">Suitability</p>
                <p className="text-xs text-indigo-900 leading-relaxed font-medium">{plan.riskProfileAnalysis?.suitability || 'N/A'}</p>
              </div>

              {/* Questionnaire Snapshot - New */}
              {plan.riskProfileAnalysis?.questionnaireSnapshot && (
                <div className="p-6 bg-slate-50/50 rounded-[2rem] border border-slate-100 space-y-4">
                  <h5 className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Questionnaire Snapshot</h5>
                  <div className="space-y-3">
                    {plan.riskProfileAnalysis.questionnaireSnapshot.map((q, i) => (
                      <div key={i} className="space-y-1">
                        <p className="text-[10px] text-slate-500 font-bold leading-tight">{q.question}</p>
                        <p className="text-xs text-slate-900 font-black">{q.answer}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Asset Allocation & Glide Path */}
          <div className="bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-sm">
            <div className="flex items-center gap-3 mb-8">
              <div className="p-2.5 bg-purple-50 text-purple-600 rounded-2xl">
                <PieIcon size={22} />
              </div>
              <div>
                <h3 className="font-bold text-slate-900">Asset Strategy</h3>
                <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Model Allocation</p>
              </div>
            </div>

            <div className="h-[220px] w-full mb-8">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={Object.entries(plan.assetAllocationStrategy?.recommended || {}).map(([name, value]) => ({ name, value }))}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={80}
                    paddingAngle={3}
                    dataKey="value"
                  >
                    {Object.keys(plan.assetAllocationStrategy?.recommended || {}).map((name, index) => (
                      <Cell key={name} fill={ASSET_COLORS[name as AssetCategory] || `hsl(${index * 45}, 70%, 60%)`} />
                    ))}
                  </Pie>
                  <RechartsTooltip 
                    formatter={(value: number) => `${isNaN(value) ? '0.0' : value.toFixed(1)}%`}
                    contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1)' }}
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>

            {plan.assetAllocationStrategy?.glidePath && (
              <div className="mb-8">
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">10-Year Glide Path</p>
                <div className="h-[150px] w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <AreaChart data={plan.assetAllocationStrategy?.glidePath || []}>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                      <XAxis dataKey="year" axisLine={false} tickLine={false} tick={{ fontSize: 9 }} />
                      <RechartsTooltip contentStyle={{ borderRadius: '12px', border: 'none', fontSize: '10px' }} />
                      <Area type="monotone" dataKey="equity" stackId="1" stroke="#6366f1" fill="#6366f1" fillOpacity={0.6} />
                      <Area type="monotone" dataKey="debt" stackId="1" stroke="#10b981" fill="#10b981" fillOpacity={0.6} />
                      <Area type="monotone" dataKey="other" stackId="1" stroke="#f59e0b" fill="#f59e0b" fillOpacity={0.6} />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>
              </div>
            )}

            <div className="p-5 bg-slate-50 rounded-2xl border border-slate-100 text-xs text-slate-600 leading-relaxed italic break-words">
              <ReactMarkdown>{plan.assetAllocationStrategy?.rebalancingSteps || ''}</ReactMarkdown>
            </div>
          </div>

          {/* Estate & Security Score */}
          <div className="bg-slate-900 p-8 rounded-[2.5rem] text-white shadow-xl">
            <div className="flex items-center gap-3 mb-8">
              <div className="p-2.5 bg-white/10 text-white rounded-2xl">
                <Lock size={22} />
              </div>
              <div>
                <h3 className="font-bold">Estate Security</h3>
                <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Wills & Nominations</p>
              </div>
            </div>

            <div className="flex items-center gap-6 mb-8">
              <div className="relative w-20 h-20">
                <svg className="w-20 h-20 transform -rotate-90">
                  <circle
                    cx="40"
                    cy="40"
                    r="36"
                    stroke="currentColor"
                    strokeWidth="8"
                    fill="transparent"
                    className="text-white/10"
                  />
                  <circle
                    cx="40"
                    cy="40"
                    r="36"
                    stroke="currentColor"
                    strokeWidth="8"
                    fill="transparent"
                    strokeDasharray={226}
                    strokeDashoffset={226 - (226 * (plan.insuranceEstatePlanning?.securityScore || 0)) / 100}
                    className="text-indigo-400 transition-all duration-1000"
                  />
                </svg>
                <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 font-black text-xl">
                  {plan.insuranceEstatePlanning?.securityScore || 0}%
                </div>
              </div>
              <div>
                <p className="text-sm font-bold mb-1">Security Score</p>
                <p className="text-[10px] text-slate-400 leading-relaxed">Based on Will status, Nominees, and Protection cover.</p>
              </div>
            </div>

            <div className="space-y-3 mb-8">
              {plan.insuranceEstatePlanning?.missingElements?.map((item, idx) => (
                <div key={idx} className="flex items-center gap-2 text-xs text-rose-300">
                  <AlertCircle size={14} />
                  <span>{item}</span>
                </div>
              ))}
              {(!plan.insuranceEstatePlanning?.missingElements || plan.insuranceEstatePlanning?.missingElements?.length === 0) && (
                <div className="flex items-center gap-2 text-xs text-emerald-400">
                  <CheckCircle2 size={14} />
                  <span>All security elements in place</span>
                </div>
              )}
            </div>

            <p className="text-xs text-slate-400 leading-relaxed italic break-words">
              {plan.insuranceEstatePlanning?.summary || 'No summary available.'}
            </p>
          </div>

          {/* Action Plan - Sidebar Version */}
          <div className="bg-indigo-600 p-8 rounded-[2.5rem] text-white shadow-2xl shadow-indigo-200">
            <div className="flex items-center gap-3 mb-8">
              <div className="p-2.5 bg-white/20 text-white rounded-2xl">
                <Zap size={22} />
              </div>
              <div>
                <h3 className="font-bold">Next Steps</h3>
                <p className="text-[10px] text-indigo-200 font-bold uppercase tracking-wider">3-6 Month Action Plan</p>
              </div>
            </div>

            <div className="space-y-8">
              {plan.actionPlan?.map((action, idx) => (
                <div key={idx} className="relative pl-8 border-l-2 border-white/20">
                  <div className="absolute top-0 left-[-5px] w-2 h-2 bg-white rounded-full shadow-[0_0_10px_rgba(255,255,255,0.8)]" />
                  <div className="flex justify-between items-center mb-2">
                    <span className={`text-[10px] font-black uppercase tracking-widest ${
                      action.priority === 'High' ? 'text-rose-300' : 'text-indigo-200'
                    }`}>
                      {action.priority} Priority
                    </span>
                    <span className="text-[10px] text-white/60 font-bold">{action.timeline}</span>
                  </div>
                  <p className="text-sm font-bold leading-relaxed mb-2">{action.step}</p>
                  <div className="flex items-center gap-2 text-[10px] text-indigo-100 bg-white/10 px-3 py-1.5 rounded-lg">
                    <TrendingUp size={12} />
                    <span className="font-medium">Impact: {action.impact}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
      {/* Future Projections & Stress Testing */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 bg-white rounded-[2.5rem] p-8 border border-slate-200 shadow-sm">
          <div className="flex items-center gap-3 mb-8">
            <div className="p-3 bg-indigo-100 rounded-2xl text-indigo-600">
              <LineIcon size={24} />
            </div>
            <div>
              <h3 className="text-xl font-bold text-slate-900">Future Wealth Projections</h3>
              <p className="text-sm text-slate-500">Projected net worth over the next 10 years</p>
            </div>
          </div>

          <div className="h-[300px] w-full mb-6">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={plan.futureProjections || []}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis 
                  dataKey="year" 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fill: '#64748b', fontSize: 12 }}
                  dy={10}
                />
                <YAxis 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fill: '#64748b', fontSize: 12 }}
                  tickFormatter={(val) => `₹${isNaN(val) ? '0.0' : (val / 10000000).toFixed(1)}Cr`}
                />
                <RechartsTooltip 
                  contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                  formatter={(val: number) => [`₹${isNaN(val) ? '0.0' : (val / 100000).toFixed(1)}L`, '']}
                />
                <Legend verticalAlign="top" align="right" iconType="circle" />
                <Line 
                  type="monotone" 
                  dataKey="projectedValue" 
                  name="Projected Net Worth" 
                  stroke="#4f46e5" 
                  strokeWidth={3} 
                  dot={{ r: 4, fill: '#4f46e5', strokeWidth: 2, stroke: '#fff' }}
                  activeDot={{ r: 6, strokeWidth: 0 }}
                />
                <Line 
                  type="monotone" 
                  dataKey="inflationAdjustedValue" 
                  name="Inflation Adjusted" 
                  stroke="#94a3b8" 
                  strokeWidth={2} 
                  strokeDasharray="5 5"
                  dot={false}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
          
          <div className="bg-slate-50 rounded-2xl p-4 flex items-start gap-3">
            <Info size={18} className="text-slate-400 mt-0.5" />
            <p className="text-xs text-slate-500 leading-relaxed">
              Projections are based on your current asset allocation, expected returns, and inflation rates. 
              Actual results may vary based on market performance and changes in your financial situation.
            </p>
          </div>
        </div>

        <div className="bg-white rounded-[2.5rem] p-8 border border-slate-200 shadow-sm">
          <div className="flex items-center gap-3 mb-8">
            <div className="p-3 bg-amber-100 rounded-2xl text-amber-600">
              <AlertTriangle size={24} />
            </div>
            <div>
              <h3 className="text-xl font-bold text-slate-900">Stress Test Analysis</h3>
              <p className="text-sm text-slate-500">Resilience against market shocks</p>
            </div>
          </div>

          <div className="prose prose-slate prose-sm max-w-none">
            <div className="markdown-body">
              <ReactMarkdown>{plan.stressTestAnalysis || 'No stress test analysis available.'}</ReactMarkdown>
            </div>
          </div>
          
          <div className="mt-8 pt-8 border-t border-slate-100">
            <div className="flex items-center justify-between mb-4">
              <span className="text-sm font-medium text-slate-600">Plan Resilience Score</span>
              <span className="text-sm font-bold text-indigo-600">8.5/10</span>
            </div>
            <div className="w-full bg-slate-100 h-2 rounded-full overflow-hidden">
              <div className="bg-indigo-600 h-full rounded-full" style={{ width: '85%' }} />
            </div>
          </div>
        </div>

        {/* Yearly Review & Minutes */}
        <div className="bg-white p-6 md:p-12 rounded-[2.5rem] md:rounded-[3.5rem] border border-slate-200 shadow-sm space-y-10">
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between border-b border-slate-100 pb-8 gap-4">
            <div className="flex items-center gap-3">
              <div className="p-3 bg-slate-100 text-slate-600 rounded-2xl">
                <Calendar size={24} />
              </div>
              <div>
                <h3 className="text-xl md:text-2xl font-black text-slate-900 tracking-tight">Yearly Review</h3>
                <p className="text-[10px] text-slate-400 font-bold uppercase tracking-[0.2em]">Minutes of Wealth Strategy Session</p>
              </div>
            </div>
            <div className="md:text-right">
              <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Date of Review</p>
              <p className="text-lg font-black text-wealth-navy">{plan.yearlyReview?.date || '09/05/2026'}</p>
            </div>
          </div>
 
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
            <div className="space-y-6">
              <h4 className="text-sm font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
                <div className="w-1.5 h-1.5 bg-wealth-navy rounded-full" />
                Points Discussed
              </h4>
              <ul className="space-y-4">
                {(plan.yearlyReview?.pointsDiscussed || [
                  "The final Comprehensive Financial Plan Explained.",
                  "PMS may be considered next year as per market conditions.",
                  "Gross professional income projections for the upcoming fiscal.",
                  "Tax efficiency through Budget 2024-25 provisions."
                ]).map((point, idx) => (
                  <li key={idx} className="flex gap-4">
                    <span className="text-xs font-black text-slate-300">{idx + 1}.</span>
                    <p className="text-sm font-bold text-slate-700 leading-relaxed">{point}</p>
                  </li>
                ))}
              </ul>
            </div>
 
            <div className="space-y-6">
              <h4 className="text-sm font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
                <div className="w-1.5 h-1.5 bg-rose-500 rounded-full" />
                Strategic Actions
              </h4>
              <div className="space-y-4">
                {(plan.yearlyReview?.strategicActions || [
                  { title: "Update Market Prices", desc: "Sync latest market values for direct equity holdings." },
                  { title: "Health Insurance review", desc: "Evaluate family floater quotations from Niva Bupa & Care." },
                  { title: "Surplus Deployment", desc: "Allocate surplus funds to Emergency fund and Debt buckets." }
                ]).map((action, idx) => (
                  <div key={idx} className="p-4 bg-slate-50 rounded-2xl border border-slate-100 flex gap-4">
                    <div className="w-8 h-8 rounded-full bg-wealth-navy text-white flex items-center justify-center text-xs font-bold shrink-0">
                      {idx + 1}
                    </div>
                    <div>
                      <p className="text-xs font-black text-slate-900 uppercase tracking-wider">{action.title}</p>
                      <p className="text-[11px] font-medium text-slate-500 mt-1">{action.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DetailedFinancialPlanView;
